### PR TITLE
Integration of Commiemod

### PR DESCRIPTION
**Pull request by willwill54**
This should be all the things which would combine our mod with Commiemod
which gives lots of flavor.

### CODE REVIEW

**Comment by LordNotix** [comment]
What features does it bring to the mod?

**Comment by willwill54** [comment]
It mainly brings flavor to communist countries. It adds events and decisions as well as some other things which I am just going to add in another commit

**Comment by Wolfenswan** [comment]
Can we create a new branch for this for testing purposes? I'm very much for it but it's a major change and could screw with the overall balance.

**Comment by Wolfenswan** [comment]
My attempt at a merge, including pop-type ideology changes and some misc. differences:
https://github.com/Wolfenswan/ParadoxPlazaMod/commit/d2ff2575f8454bf75763a84f50d99e2b97ae3b6a

**Pull request merged**
